AWSTemplateFormatVersion: '2010-09-09'
Resources:
  RestApi:
    Type: AWS::ApiGateway::RestApi
    Properties:
      Name: QuarkusRestApi

  RootMethod:
    Type: AWS::ApiGateway::Method
    Properties:
      AuthorizationType: NONE
      HttpMethod: ANY
      ResourceId:
        Fn::GetAtt:
          - RestApi
          - RootResourceId
      RestApiId:
        Ref: RestApi

  Integration:
    Type: AWS::ApiGateway::Integration
    Properties:
      IntegrationHttpMethod: POST  # Modify as needed
      Type: AWS_PROXY
      Uri: arn:aws:apigateway:eu-west-1:lambda:path/2015-03-31/functions/your-lambda-function-arn/invocations
      IntegrationResponses:
        - StatusCode: 200

  IntegrationResponse:
    Type: AWS::ApiGateway::IntegrationResponse
    Properties:
      StatusCode: 200
      ResponseTemplates:
        application/json: ''

  MethodResponse:
    Type: AWS::ApiGateway::MethodResponse
    Properties:
      HttpMethod: ANY
      ResourceId:
        Fn::GetAtt:
          - RestApi
          - RootResourceId
      RestApiId:
        Ref: RestApi
      StatusCode: 200

  Deployment:
    Type: AWS::ApiGateway::Deployment
    DependsOn:
      - IntegrationResponse
    Properties:
      RestApiId:
        Ref: RestApi

  Stage:
    Type: AWS::ApiGateway::Stage
    Properties:
      DeploymentId:
        Ref: Deployment
      RestApiId:
        Ref: RestApi
      StageName: prod
