AWSTemplateFormatVersion: '2010-09-09'
Resources:
  EcsCluster:
    Type: AWS::ECS::Cluster

  EcsTaskDefinition:
    Type: AWS::ECS::TaskDefinition
    Properties:
      Family: github-data-api
      NetworkMode: awsvpc
      RequiresCompatibilities:
        - FARGATE
      ExecutionRoleArn: <execution-role-arn>
      TaskRoleArn: <task-role-arn>
      Cpu: '256'
      Memory: '512'
      ContainerDefinitions:
        - Name: quarkus-rest-container
          Image: <docker-image-uri>
          PortMappings:
            - ContainerPort: 8080
          LogConfiguration:
            LogDriver: awslogs
            Options:
              awslogs-group: <log-group-name>
              awslogs-region: <aws-region>

  EcsService:
    Type: AWS::ECS::Service
    Properties:
      Cluster: !Ref EcsCluster
      DesiredCount: 1
      TaskDefinition: !Ref EcsTaskDefinition
